[package]
name = "proc-macro-workshop"
version = "0.0.0"
edition = "2021"
publish = false

[workspace]
members = [
    "bitfield",
    "builder",
    "debug",
    "seq",
    "seq_lib",
    "sorted",
]

[[bin]]
name = "workshop"
path = "main.rs"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

seq_lib = { path = "seq_lib" }

[workspace.dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }
