[package]
name = "bitfield_lib"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }
